### ISSUE TITLE
works wrong: 

### ISSUE THREAD

**Issue by MojtabaFarsian** [thisissepehr/LFJ-LFM#1]
this example is wrong:

user.addTask(1, [0, 1, 2])
user.addTask(5, [0, 1])
user.addTask(6, [2])
user.addTask(11, [0, 1, 2])
user.addTask(1, [1])

see this algorithm: https://github.com/daniyal2959/lfm-lfj

**Comment by thisissepehr** [comment]
Hi, Considering that taking a task off or on takes 1 unit of time for the machine, this algorithm works fine. Although it is worth noting that CPM shows the maximum amount of time a machine has spent working on tasks not changing between them. I have changed the reporting part for clearing the confusion.

**Comment by thisissepehr** [comment]
> this example is wrong:
> 
> user.addTask(1, [0, 1, 2]) user.addTask(5, [0, 1]) user.addTask(6, [2]) user.addTask(11, [0, 1, 2]) user.addTask(1, [1])
> 
> see this algorithm: https://github.com/daniyal2959/lfm-lfj

Hi, Considering that taking a task off or on takes 1 unit of time for the machine, this algorithm works fine. Although it is worth noting that CPM shows the maximum amount of time a machine has spent working on tasks not changing between them. I have changed the reporting part for clearing the confusion.
